apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "snaplogic-snaplex.name" . }}-jccfeedmastermonitoring"
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
    positions:
      filename: /var/log/positions.yaml 

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name:  sljcclogs
        static_configs: 
          - targets: 
              - localhost 
            labels:
              job: sljcclogs
              __path__: /opt/snaplogic/run/log/jcc.json # Any file .log in the EmptyDir Volume.

      - job_name:  slfeedmasterlogs
        static_configs: 
          - targets: 
              - localhost 
            labels:
              job: slfeedmasterlogs
              __path__: /opt/snaplogic/run/log/feed_master.json