name: Docker Image Tag CI Build Push

on:
  push:
    tags:
    - '*'

jobs:

  build:


    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Docker/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USER}}/sl:${{github.ref_name}}
    
    - name: Replace image tag in manifest file
      run: |
        sudo snap install yq
        cd charts/sl_helm_chart_v3
        export IMAGE_TAG=${{github.ref_name}}
        yq e -i '.image.tag = "IMAGE_TAG"' values.yaml

    - name: Commit changes to the repository
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add .
        git commit -m "Changed image version in values yaml file to version ${{github.ref_name}}"
        git push origin HEAD:main
        
        
        